import type { Metadata } from "next";
import { Inter, Playfair } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Navbar from "../components/Navbar";
import { cn } from "@/lib/utils";
import AuthSessionProvider from "@/components/auth/AuthSessionProvider";
import { Toaster } from "sonner";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavbarFallback = () => (
  <nav className='sticky top-0 z-50 h-16 border-b border-[#DAD3C8] bg-[#FCFAF7]/50 backdrop-blur-xs' />
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className={`${playfair.className} antialiased bg-[#FBFAF8]!`}>
        <Suspense fallback={<NavbarFallback />}>
          <AuthSessionProvider>
            <Navbar />
            {children}
          </AuthSessionProvider>
        </Suspense>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
